baseURL = 'https://sreeraminsights.github.io/blog/'
languageCode = 'en-us'
title = "Sreeram's blog"
theme = "papercss-hugo-theme"
[permalinks]
    post = "/blog/:slug"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 10

  [[menu.main]]
    name = "Videos"
    url = "/videos"
    weight = 20

  [[menu.main]]
    name = "Uses"
    url = "/uses"
    weight = 30

  [[menu.main]]
    name = "Links"
    url = "/links"
    weight = 40

  [[menu.main]]
    name = "Contact"
    url = "sreeraminsights@gmail.com"
    weight = 50


  [[menu.social]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/sreeraminsights"
    weight = 10

  [[menu.social]]
    name = "YouTube"
    pre = "youtube"
    url = "https://youtube.com/@sreeraminsights"
    weight = 20


[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    style = 'catppuccin-macchiato'
